# Generated by Django 3.1.4 on 2021-03-15 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BMsite', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Problem',
        ),
    ]
