# Generated by Django 3.1.4 on 2021-03-16 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BMsite', '0003_problems'),
    ]

    operations = [
        migrations.DeleteModel(
            name='problems',
        ),
    ]
