# Generated by Django 3.1.4 on 2021-03-16 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('BMsite', '0004_delete_problems'),
    ]

    operations = [
        migrations.CreateModel(
            name='bm_problems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.CharField(max_length=20)),
                ('subject', models.CharField(max_length=20)),
                ('problem', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('empid', models.CharField(max_length=20)),
            ],
        ),
    ]
