# Generated by Django 3.1.4 on 2021-03-17 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BMsite', '0005_bm_problems'),
    ]

    operations = [
        migrations.DeleteModel(
            name='bm_problems',
        ),
    ]
