# Generated by Django 3.1.4 on 2021-03-17 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BMsite', '0008_customers'),
    ]

    operations = [
        migrations.CreateModel(
            name='loans',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Year', models.CharField(max_length=10)),
                ('bapunagar_loans', models.CharField(max_length=10)),
                ('bopal_loans', models.CharField(max_length=10)),
                ('chandkheda_loans', models.CharField(max_length=10)),
                ('gandhinagar_loans', models.CharField(max_length=10)),
                ('gota_loans', models.CharField(max_length=10)),
                ('isanpur_loans', models.CharField(max_length=10)),
                ('lal_darwaja_loans', models.CharField(max_length=10)),
                ('maninagar_loans', models.CharField(max_length=10)),
                ('vastral_loans', models.CharField(max_length=10)),
            ],
        ),
    ]
