# Generated by Django 3.1.4 on 2021-02-25 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch_Sheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Acct_branch', models.CharField(max_length=50)),
                ('Branch_number', models.CharField(max_length=25)),
                ('Transaction_code', models.IntegerField()),
                ('Transaction_code_desc', models.CharField(max_length=10)),
                ('Post_date', models.CharField(max_length=20)),
                ('Amount', models.IntegerField()),
                ('Debit_credit', models.CharField(max_length=3)),
            ],
        ),
    ]
