# Generated by Django 3.1.4 on 2021-03-15 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BHQsite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch_sheet',
            name='Transaction_code',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='branch_sheet',
            name='Transaction_code_desc',
            field=models.CharField(max_length=30),
        ),
    ]
