# Generated by Django 3.1.4 on 2021-03-16 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BHQsite', '0003_bhq_problems'),
    ]

    operations = [
        migrations.DeleteModel(
            name='bhq_problems',
        ),
    ]
