# Generated by Django 3.1.4 on 2021-03-16 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BHQsite', '0005_bhqproblems'),
    ]

    operations = [
        migrations.DeleteModel(
            name='bhqproblems',
        ),
    ]
