# Generated by Django 3.1.4 on 2021-03-17 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BHQsite', '0006_delete_bhqproblems'),
    ]

    operations = [
        migrations.CreateModel(
            name='bhq_problems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empid', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=50)),
                ('branch', models.CharField(max_length=20)),
                ('subject', models.CharField(max_length=20)),
                ('problem', models.CharField(max_length=300)),
            ],
        ),
    ]
