# Generated by Django 3.1.4 on 2021-03-17 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BHQsite', '0007_bhq_problems'),
    ]

    operations = [
        migrations.CreateModel(
            name='deposits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Year', models.CharField(max_length=10)),
                ('Bapunagar_Deposits', models.CharField(max_length=10)),
                ('Bopal_Deposits', models.CharField(max_length=10)),
                ('Chandkheda_Deposits', models.CharField(max_length=10)),
                ('Gandhinagar_Deposits', models.CharField(max_length=10)),
                ('Gota_Deposits', models.CharField(max_length=10)),
                ('Isanpur_Deposits', models.CharField(max_length=10)),
                ('Lal_Darwaja_Deposits', models.CharField(max_length=10)),
                ('Maninagar_Deposits', models.CharField(max_length=10)),
                ('Vastral_Deposits', models.CharField(max_length=10)),
            ],
        ),
    ]
